INFO 2024-02-08 19:11:42,202 autoreload 9716 13824 Watching for file changes with StatReloader
INFO 2024-02-08 19:11:48,136 basehttp 9716 15640 "GET /about/ HTTP/1.1" 200 308
INFO 2024-02-08 19:11:51,023 basehttp 9716 15640 "GET /about/ HTTP/1.1" 200 308
INFO 2024-02-08 19:13:26,295 autoreload 12860 3612 Watching for file changes with StatReloader
INFO 2024-02-08 19:13:31,638 basehttp 12860 13168 "GET /about/ HTTP/1.1" 200 308
INFO 2024-02-08 19:13:32,152 basehttp 12860 13168 "GET /about/ HTTP/1.1" 200 308
INFO 2024-02-08 19:13:32,579 basehttp 12860 13168 "GET /about/ HTTP/1.1" 200 308
INFO 2024-02-08 19:14:01,779 basehttp 12860 13168 "GET / HTTP/1.1" 200 388
INFO 2024-02-08 19:14:05,486 basehttp 12860 13168 "GET /about/ HTTP/1.1" 200 308
INFO 2024-02-08 19:14:10,493 basehttp 12860 13168 "GET / HTTP/1.1" 200 388
INFO 2024-02-08 19:14:23,992 basehttp 12860 13168 "GET / HTTP/1.1" 200 388
INFO 2024-02-08 19:14:24,850 basehttp 12860 13168 "GET / HTTP/1.1" 200 388
INFO 2024-02-08 19:14:32,678 basehttp 12860 13168 "GET / HTTP/1.1" 200 388
INFO 2024-02-08 19:14:33,672 basehttp 12860 13168 "GET / HTTP/1.1" 200 388
INFO 2024-02-13 05:16:26,296 autoreload 13176 11520 Watching for file changes with StatReloader
INFO 2024-02-13 05:16:36,562 basehttp 13176 684 "GET / HTTP/1.1" 200 388
INFO 2024-02-13 05:16:38,684 basehttp 13176 684 "GET / HTTP/1.1" 200 388
INFO 2024-02-13 05:16:44,495 basehttp 13176 684 "GET /about/ HTTP/1.1" 200 308
INFO 2024-02-13 05:16:46,123 basehttp 13176 684 "GET /about/ HTTP/1.1" 200 308
INFO 2024-02-13 05:16:47,743 basehttp 13176 684 "GET /about/ HTTP/1.1" 200 308
INFO 2024-02-15 00:06:18,792 autoreload 8088 12604 Watching for file changes with StatReloader
INFO 2024-02-15 00:06:22,862 basehttp 8088 12828 "GET / HTTP/1.1" 200 388
INFO 2024-02-15 00:06:24,906 basehttp 8088 12828 "GET / HTTP/1.1" 200 388
INFO 2024-02-17 21:50:13,859 autoreload 8036 16292 Watching for file changes with StatReloader
INFO 2024-02-17 21:50:16,878 basehttp 8036 21764 "GET / HTTP/1.1" 200 388
INFO 2024-02-17 21:50:23,682 basehttp 8036 21764 "GET /about/ HTTP/1.1" 200 308
INFO 2024-02-18 23:50:53,935 autoreload 17116 23268 Watching for file changes with StatReloader
INFO 2024-02-18 23:50:56,275 basehttp 17116 21640 "GET / HTTP/1.1" 200 388
WARNING 2024-02-18 23:50:56,549 log 17116 21640 Not Found: /favicon.ico
WARNING 2024-02-18 23:50:56,550 basehttp 17116 21640 "GET /favicon.ico HTTP/1.1" 404 2548
INFO 2024-02-18 23:51:06,530 basehttp 17116 21640 "GET /about/ HTTP/1.1" 200 308
INFO 2024-02-18 23:51:19,958 basehttp 17116 21640 "GET /admin/ HTTP/1.1" 302 0
INFO 2024-02-18 23:51:20,233 basehttp 17116 21640 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
INFO 2024-02-18 23:51:20,268 basehttp 17116 21640 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2024-02-18 23:51:20,268 basehttp 17116 21080 "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2024-02-18 23:51:20,269 basehttp 17116 18748 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2024-02-18 23:51:20,269 basehttp 17116 15316 "GET /static/admin/css/login.css HTTP/1.1" 304 0
INFO 2024-02-18 23:51:20,269 basehttp 17116 1520 "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2024-02-18 23:51:20,269 basehttp 17116 15048 "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2024-02-18 23:51:20,269 basehttp 17116 15316 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
WARNING 2024-02-18 23:51:36,678 log 17116 15316 Not Found: /myapp2/
WARNING 2024-02-18 23:51:36,679 basehttp 17116 15316 "GET /myapp2/ HTTP/1.1" 404 2536
INFO 2024-02-18 23:51:43,425 basehttp 17116 15316 "GET /myapp3/ HTTP/1.1" 200 337
INFO 2024-02-18 23:52:25,902 autoreload 17116 23268 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO 2024-02-18 23:52:26,690 autoreload 22900 22112 Watching for file changes with StatReloader
INFO 2024-02-18 23:52:27,014 basehttp 22900 13636 "GET /myapp3/ HTTP/1.1" 200 337
INFO 2024-02-18 23:52:35,241 basehttp 22900 13636 "GET /myapp3/ HTTP/1.1" 200 337
INFO 2024-02-18 23:52:49,946 basehttp 22900 13636 "GET / HTTP/1.1" 200 388
INFO 2024-02-18 23:52:51,274 basehttp 22900 13636 "GET / HTTP/1.1" 200 388
WARNING 2024-02-18 23:53:01,464 log 22900 13636 Not Found: /myapp2/
WARNING 2024-02-18 23:53:01,465 basehttp 22900 13636 "GET /myapp2/ HTTP/1.1" 404 2536
INFO 2024-02-18 23:53:04,125 basehttp 22900 13636 "GET /myapp3/ HTTP/1.1" 200 337
INFO 2024-02-18 23:53:06,677 basehttp 22900 13636 "GET /myapp3/ HTTP/1.1" 200 337
INFO 2024-02-18 23:53:26,864 autoreload 22900 22112 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO 2024-02-18 23:53:27,507 autoreload 16284 15872 Watching for file changes with StatReloader
INFO 2024-02-18 23:53:28,780 basehttp 16284 18072 "GET /myapp3/ HTTP/1.1" 200 337
INFO 2024-02-19 00:27:39,558 autoreload 14452 17420 Watching for file changes with StatReloader
INFO 2024-02-19 00:27:43,026 basehttp 14452 24508 "GET /myapp3/client_orders/3/ HTTP/1.1" 200 412
INFO 2024-02-19 00:28:17,979 basehttp 14452 24508 "GET /myapp3/client_orders/1/ HTTP/1.1" 200 412
INFO 2024-02-19 00:28:29,273 basehttp 14452 24508 "GET /myapp3/client_orders/2/ HTTP/1.1" 200 412
INFO 2024-02-19 00:29:24,904 basehttp 14452 24508 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 412
ERROR 2024-02-19 00:30:09,014 log 14452 24508 Internal Server Error: /myapp3/client_orders/52/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py", line 11, in client_orders
    client = Client.objects.get(pk=client_id)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
myapp3.models.Client.DoesNotExist: Client matching query does not exist.
ERROR 2024-02-19 00:30:09,017 basehttp 14452 24508 "GET /myapp3/client_orders/52/ HTTP/1.1" 500 74918
INFO 2024-02-19 00:30:16,246 basehttp 14452 24508 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 00:41:08,161 autoreload 22224 19760 Watching for file changes with StatReloader
INFO 2024-02-19 00:41:10,340 basehttp 22224 21628 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 00:41:11,661 basehttp 22224 21628 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 00:41:12,846 basehttp 22224 21628 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 00:41:27,045 basehttp 22224 21628 "GET /myapp3/client_orders/42 HTTP/1.1" 301 0
ERROR 2024-02-19 00:41:27,082 log 22224 18548 Internal Server Error: /myapp3/client_orders/42/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py", line 11, in client_orders
    client = Client.objects.get(pk=client_id)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
myapp3.models.Client.DoesNotExist: Client matching query does not exist.
ERROR 2024-02-19 00:41:27,085 basehttp 22224 18548 "GET /myapp3/client_orders/42/ HTTP/1.1" 500 74918
INFO 2024-02-19 00:41:33,437 basehttp 22224 18548 "GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO 2024-02-19 00:42:53,634 autoreload 22224 19760 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO 2024-02-19 00:42:54,395 autoreload 21784 21560 Watching for file changes with StatReloader
INFO 2024-02-19 00:45:38,316 basehttp 21784 23564 "GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO 2024-02-19 00:45:39,652 basehttp 21784 23564 "GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO 2024-02-19 00:46:33,931 basehttp 21784 23564 "GET /myapp3/client_orders/4/ HTTP/1.1" 200 436
INFO 2024-02-19 00:50:54,589 autoreload 21784 21560 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO 2024-02-19 00:50:55,250 autoreload 20148 17136 Watching for file changes with StatReloader
INFO 2024-02-19 00:50:57,358 basehttp 20148 15456 "GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO 2024-02-19 00:50:58,629 basehttp 20148 15456 "GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO 2024-02-19 00:50:59,878 basehttp 20148 15456 "GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO 2024-02-19 00:56:45,474 basehttp 20148 24056 "GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO 2024-02-19 00:56:46,086 basehttp 20148 24056 "GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO 2024-02-19 00:56:46,553 basehttp 20148 24056 "GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO 2024-02-19 00:56:46,816 basehttp 20148 24056 "GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO 2024-02-19 00:56:47,043 basehttp 20148 24056 "GET /myapp3/client_orders/4/ HTTP/1.1" 200 412
INFO 2024-02-19 00:57:54,208 basehttp 20148 24056 "GET / HTTP/1.1" 200 388
WARNING 2024-02-19 00:58:06,905 log 20148 24056 Not Found: /myapp2/
WARNING 2024-02-19 00:58:06,905 basehttp 20148 24056 "GET /myapp2/ HTTP/1.1" 404 2536
WARNING 2024-02-19 00:58:12,169 log 20148 24056 Not Found: /myapp2/3
WARNING 2024-02-19 00:58:12,170 basehttp 20148 24056 "GET /myapp2/3 HTTP/1.1" 404 2539
WARNING 2024-02-19 00:58:28,119 log 20148 24056 Not Found: /myapp2/
WARNING 2024-02-19 00:58:28,119 basehttp 20148 24056 "GET /myapp2/ HTTP/1.1" 404 2536
WARNING 2024-02-19 00:58:34,518 log 20148 24056 Not Found: /myapp2/client_orders/5/
WARNING 2024-02-19 00:58:34,518 basehttp 20148 24056 "GET /myapp2/client_orders/5/ HTTP/1.1" 404 2584
INFO 2024-02-19 01:00:21,746 autoreload 16796 18344 Watching for file changes with StatReloader
INFO 2024-02-19 01:00:47,455 basehttp 16796 25176 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:00:49,452 basehttp 16796 25176 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:00:49,958 basehttp 16796 25176 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:00:50,352 basehttp 16796 25176 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:00:50,617 basehttp 16796 25176 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:00:50,874 basehttp 16796 25176 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:02:22,081 basehttp 16796 25176 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:02:23,108 basehttp 16796 25176 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:02:24,081 basehttp 16796 25176 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:02:24,898 basehttp 16796 25176 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:03:18,524 autoreload 16796 18344 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO 2024-02-19 01:03:19,160 autoreload 15872 24044 Watching for file changes with StatReloader
INFO 2024-02-19 01:03:23,849 basehttp 15872 14792 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:03:24,663 basehttp 15872 14792 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:03:25,248 basehttp 15872 14792 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:03:25,689 basehttp 15872 14792 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:09:55,782 autoreload 19980 22532 Watching for file changes with StatReloader
INFO 2024-02-19 01:09:59,043 basehttp 19980 15144 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:10:00,634 basehttp 19980 15144 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:10:01,208 basehttp 19980 15144 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:10:02,175 basehttp 19980 15144 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:10:03,440 basehttp 19980 15144 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:11:53,895 autoreload 16496 19192 Watching for file changes with StatReloader
INFO 2024-02-19 01:11:56,886 basehttp 16496 22104 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:11:58,204 basehttp 16496 22104 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:11:58,764 basehttp 16496 22104 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:11:59,281 basehttp 16496 22104 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
INFO 2024-02-19 01:11:59,559 basehttp 16496 22104 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 412
WARNING 2024-02-19 01:12:09,707 log 16496 22104 Not Found: /myapp3/client_orders/
WARNING 2024-02-19 01:12:09,708 basehttp 16496 22104 "GET /myapp3/client_orders/ HTTP/1.1" 404 2852
INFO 2024-02-19 01:12:14,338 basehttp 16496 22104 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 412
INFO 2024-02-19 01:18:24,508 autoreload 16496 19192 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myproject\urls.py changed, reloading.
INFO 2024-02-19 01:18:25,144 autoreload 23572 24680 Watching for file changes with StatReloader
INFO 2024-02-19 01:21:05,147 autoreload 8716 17284 Watching for file changes with StatReloader
INFO 2024-02-19 01:21:09,058 basehttp 8716 24120 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 412
INFO 2024-02-19 01:21:10,331 basehttp 8716 24120 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 412
INFO 2024-02-19 01:21:10,800 basehttp 8716 24120 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 412
INFO 2024-02-19 01:21:11,383 basehttp 8716 24120 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 412
INFO 2024-02-19 01:21:52,238 basehttp 8716 24120 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 412
INFO 2024-02-19 01:21:52,850 basehttp 8716 24120 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 412
INFO 2024-02-19 01:23:25,854 basehttp 8716 24120 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:23:26,469 basehttp 8716 24120 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:24:08,986 basehttp 8716 24120 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:24:09,993 basehttp 8716 24120 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:24:10,940 basehttp 8716 24120 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:24:11,635 basehttp 8716 24120 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:24:12,428 basehttp 8716 24120 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:26:01,123 autoreload 8716 17284 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO 2024-02-19 01:26:01,750 autoreload 19460 23376 Watching for file changes with StatReloader
INFO 2024-02-19 01:26:23,742 autoreload 19460 23376 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO 2024-02-19 01:26:24,332 autoreload 16436 20592 Watching for file changes with StatReloader
INFO 2024-02-19 01:26:50,743 autoreload 16436 20592 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO 2024-02-19 01:26:51,349 autoreload 22544 24764 Watching for file changes with StatReloader
ERROR 2024-02-19 01:26:55,813 log 22544 16952 Internal Server Error: /myapp3/client_orders/10/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py", line 18, in client_orders
    seven_days_ago = timezone.now() - timedelta(days=7)
NameError: name 'timezone' is not defined
ERROR 2024-02-19 01:26:55,815 basehttp 22544 16952 "GET /myapp3/client_orders/10/ HTTP/1.1" 500 66301
ERROR 2024-02-19 01:27:12,072 log 22544 16952 Internal Server Error: /myapp3/client_orders/10/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py", line 18, in client_orders
    seven_days_ago = timezone.now() - timedelta(days=7)
NameError: name 'timezone' is not defined
ERROR 2024-02-19 01:27:12,075 basehttp 22544 16952 "GET /myapp3/client_orders/10/ HTTP/1.1" 500 66301
INFO 2024-02-19 01:27:12,912 autoreload 22544 24764 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO 2024-02-19 01:27:13,562 autoreload 15700 19580 Watching for file changes with StatReloader
INFO 2024-02-19 01:27:14,969 basehttp 15700 15876 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:27:46,511 basehttp 15700 15876 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:27:46,668 autoreload 15700 19580 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO 2024-02-19 01:27:47,462 autoreload 16796 25148 Watching for file changes with StatReloader
INFO 2024-02-19 01:28:16,805 autoreload 16796 25148 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO 2024-02-19 01:28:17,420 autoreload 21280 20028 Watching for file changes with StatReloader
INFO 2024-02-19 01:28:19,487 basehttp 21280 24644 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:28:23,393 basehttp 21280 24644 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:28:24,056 basehttp 21280 24644 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:29:49,108 autoreload 21280 20028 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO 2024-02-19 01:29:49,715 autoreload 25144 16008 Watching for file changes with StatReloader
INFO 2024-02-19 01:29:52,170 basehttp 25144 25452 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:29:53,316 basehttp 25144 25452 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:29:54,646 basehttp 25144 25452 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:29:56,474 basehttp 25144 25452 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:31:30,176 basehttp 25144 25452 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:31:30,782 autoreload 25144 16008 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO 2024-02-19 01:31:31,480 autoreload 24588 22212 Watching for file changes with StatReloader
INFO 2024-02-19 01:31:31,769 basehttp 24588 13672 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:31:33,323 basehttp 24588 13672 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:31:34,099 basehttp 24588 13672 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:31:51,831 autoreload 24588 22212 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO 2024-02-19 01:31:52,451 autoreload 14452 23708 Watching for file changes with StatReloader
ERROR 2024-02-19 01:31:54,879 log 14452 8612 Internal Server Error: /myapp3/client_orders/10/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py", line 32, in client_orders
    return render(request, 'orders.html', context)
NameError: name 'render' is not defined
ERROR 2024-02-19 01:31:54,882 basehttp 14452 8612 "GET /myapp3/client_orders/10/ HTTP/1.1" 500 67772
INFO 2024-02-19 01:33:06,362 autoreload 14452 23708 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO 2024-02-19 01:33:06,963 autoreload 24936 24912 Watching for file changes with StatReloader
INFO 2024-02-19 01:33:10,721 basehttp 24936 20380 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:33:11,535 basehttp 24936 20380 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:33:12,230 basehttp 24936 20380 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:35:48,972 autoreload 22604 15168 Watching for file changes with StatReloader
INFO 2024-02-19 01:35:52,573 basehttp 22604 21440 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:35:53,384 basehttp 22604 21440 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:35:53,968 basehttp 22604 21440 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:35:54,411 basehttp 22604 21440 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 01:35:59,788 basehttp 22604 21440 "GET /myapp3/client_orders/1 HTTP/1.1" 301 0
INFO 2024-02-19 01:35:59,800 basehttp 22604 17716 "GET /myapp3/client_orders/1/ HTTP/1.1" 200 360
INFO 2024-02-19 01:36:02,667 basehttp 22604 17716 "GET /myapp3/client_orders/1/ HTTP/1.1" 200 360
INFO 2024-02-19 01:36:03,226 basehttp 22604 17716 "GET /myapp3/client_orders/1/ HTTP/1.1" 200 360
INFO 2024-02-19 01:37:11,346 basehttp 22604 17716 "GET /myapp3/client_orders/1/ HTTP/1.1" 200 360
INFO 2024-02-19 01:37:11,989 basehttp 22604 17716 "GET /myapp3/client_orders/1/ HTTP/1.1" 200 360
INFO 2024-02-19 01:37:12,479 basehttp 22604 17716 "GET /myapp3/client_orders/1/ HTTP/1.1" 200 360
INFO 2024-02-19 01:37:12,871 basehttp 22604 17716 "GET /myapp3/client_orders/1/ HTTP/1.1" 200 360
INFO 2024-02-19 01:37:50,748 autoreload 22604 15168 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO 2024-02-19 01:37:51,394 autoreload 18924 17892 Watching for file changes with StatReloader
ERROR 2024-02-19 01:37:54,497 log 18924 24600 Internal Server Error: /myapp3/client_orders/1/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py", line 16, in client_orders
    seven_days_ago = timezone.now() - timedelta(days=7)
AttributeError: type object 'datetime.timezone' has no attribute 'now'
ERROR 2024-02-19 01:37:54,498 basehttp 18924 24600 "GET /myapp3/client_orders/1/ HTTP/1.1" 500 66453
INFO 2024-02-19 01:38:08,881 autoreload 18924 17892 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO 2024-02-19 01:38:09,499 autoreload 22720 4120 Watching for file changes with StatReloader
INFO 2024-02-19 01:38:12,024 basehttp 22720 22880 "GET /myapp3/client_orders/1/ HTTP/1.1" 200 360
INFO 2024-02-19 01:38:12,939 basehttp 22720 22880 "GET /myapp3/client_orders/1/ HTTP/1.1" 200 360
INFO 2024-02-19 02:02:55,513 autoreload 13136 23904 Watching for file changes with StatReloader
INFO 2024-02-19 02:05:46,278 autoreload 13136 23904 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO 2024-02-19 02:05:46,954 autoreload 22756 15884 Watching for file changes with StatReloader
INFO 2024-02-19 02:07:16,992 basehttp 22756 22988 "GET /myapp3/ HTTP/1.1" 200 337
WARNING 2024-02-19 02:07:35,685 log 22756 22988 Not Found: /myapp3/2
WARNING 2024-02-19 02:07:35,687 basehttp 22756 22988 "GET /myapp3/2 HTTP/1.1" 404 2813
INFO 2024-02-19 02:07:44,370 basehttp 22756 22988 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 02:07:46,463 basehttp 22756 22988 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 02:07:46,954 basehttp 22756 22988 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 02:08:30,850 autoreload 22756 15884 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp3\views.py changed, reloading.
INFO 2024-02-19 02:08:31,479 autoreload 25404 24564 Watching for file changes with StatReloader
INFO 2024-02-19 02:11:21,488 autoreload 21248 18792 Watching for file changes with StatReloader
INFO 2024-02-19 02:11:25,995 basehttp 21248 21892 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 02:11:26,589 basehttp 21248 21892 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 02:11:27,042 basehttp 21248 21892 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 02:11:27,269 basehttp 21248 21892 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 360
INFO 2024-02-19 02:15:23,355 basehttp 21248 21892 "GET /myapp3/client_orders/10/ HTTP/1.1" 200 388
INFO 2024-02-19 08:49:40,252 autoreload 15644 15048 Watching for file changes with StatReloader
INFO 2024-02-19 08:49:42,106 basehttp 15644 12812 "GET / HTTP/1.1" 200 388
WARNING 2024-02-19 08:49:42,273 log 15644 12812 Not Found: /favicon.ico
WARNING 2024-02-19 08:49:42,274 basehttp 15644 12812 "GET /favicon.ico HTTP/1.1" 404 2548
WARNING 2024-02-19 08:49:59,188 log 15644 12812 Not Found: /myapp2/
WARNING 2024-02-19 08:49:59,189 basehttp 15644 12812 "GET /myapp2/ HTTP/1.1" 404 2536
INFO 2024-02-19 08:50:03,446 basehttp 15644 12812 "GET /myapp3/ HTTP/1.1" 200 337
INFO 2024-02-19 08:50:23,336 basehttp 15644 12812 "GET /myapp3/client_orders/5/ HTTP/1.1" 200 388
INFO 2024-02-19 08:50:35,730 basehttp 15644 12812 "GET /myapp3/client_orders/6/ HTTP/1.1" 200 772
INFO 2024-02-19 08:50:52,080 basehttp 15644 12812 "GET /myapp3/client_orders/7/ HTTP/1.1" 200 388
INFO 2024-02-19 08:51:03,712 basehttp 15644 12812 "GET /myapp3/client_orders/8/ HTTP/1.1" 200 388
INFO 2024-02-19 08:51:15,016 basehttp 15644 12812 "GET /myapp3/client_orders/6/ HTTP/1.1" 200 772
INFO 2024-02-19 08:59:04,251 basehttp 15644 7084 "GET /myapp3/client_orders/7/ HTTP/1.1" 200 388
INFO 2024-02-20 21:46:32,745 autoreload 15588 14952 Watching for file changes with StatReloader
INFO 2024-02-20 21:46:35,120 basehttp 15588 15456 "GET / HTTP/1.1" 200 388
WARNING 2024-02-20 21:46:35,346 log 15588 15456 Not Found: /favicon.ico
WARNING 2024-02-20 21:46:35,347 basehttp 15588 15456 "GET /favicon.ico HTTP/1.1" 404 2655
WARNING 2024-02-20 21:47:19,590 log 15588 15456 Not Found: /myapp4/
WARNING 2024-02-20 21:47:19,591 basehttp 15588 15456 "GET /myapp4/ HTTP/1.1" 404 2717
ERROR 2024-02-20 21:48:13,217 log 15588 15456 Internal Server Error: /myapp4/user/add/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py", line 20, in form_app4
    return render(request, 'myapp4/form_app4.html', {'form': form})
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp4/form_app4.html
ERROR 2024-02-20 21:48:13,220 basehttp 15588 15456 "GET /myapp4/user/add/ HTTP/1.1" 500 81161
WARNING 2024-02-20 21:48:27,463 log 15588 15456 Not Found: /user/add/
WARNING 2024-02-20 21:48:27,464 basehttp 15588 15456 "GET /user/add/ HTTP/1.1" 404 2649
INFO 2024-02-20 21:49:00,645 autoreload 15588 14952 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myproject\urls.py changed, reloading.
INFO 2024-02-20 21:49:01,321 autoreload 8340 8124 Watching for file changes with StatReloader
ERROR 2024-02-20 21:49:23,069 log 8340 10236 Internal Server Error: /user/add/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py", line 20, in form_app4
    return render(request, 'myapp4/form_app4.html', {'form': form})
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp4/form_app4.html
ERROR 2024-02-20 21:49:23,073 basehttp 8340 10236 "GET /user/add/ HTTP/1.1" 500 81214
INFO 2024-02-20 21:54:20,091 autoreload 8340 8124 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py changed, reloading.
INFO 2024-02-20 21:54:20,762 autoreload 11612 4756 Watching for file changes with StatReloader
INFO 2024-02-20 21:54:26,348 basehttp 11612 9512 "GET /user/add/ HTTP/1.1" 200 729
INFO 2024-02-20 21:55:58,644 basehttp 11612 9512 "GET /user/add/ HTTP/1.1" 200 776
INFO 2024-02-20 21:57:22,555 basehttp 11612 9512 "POST /user/add/ HTTP/1.1" 200 835
INFO 2024-02-20 21:57:33,377 basehttp 11612 9512 "POST /user/add/ HTTP/1.1" 200 835
INFO 2024-02-20 22:01:35,446 autoreload 9868 9076 Watching for file changes with StatReloader
INFO 2024-02-20 22:01:39,188 basehttp 9868 2260 "GET / HTTP/1.1" 200 388
WARNING 2024-02-20 22:01:57,485 log 9868 2260 Not Found: /users/
WARNING 2024-02-20 22:01:57,486 basehttp 9868 2260 "GET /users/ HTTP/1.1" 404 2707
WARNING 2024-02-20 22:02:08,576 log 9868 2260 Not Found: /users/add/
WARNING 2024-02-20 22:02:08,578 basehttp 9868 2260 "GET /users/add/ HTTP/1.1" 404 2719
WARNING 2024-02-20 22:02:17,544 log 9868 2260 Not Found: /users/add/
WARNING 2024-02-20 22:02:17,545 basehttp 9868 2260 "GET /users/add/ HTTP/1.1" 404 2719
INFO 2024-02-20 22:02:52,283 basehttp 9868 2260 "GET /user/add/ HTTP/1.1" 200 776
INFO 2024-02-20 22:03:12,474 basehttp 9868 2260 "POST /user/add/ HTTP/1.1" 200 827
INFO 2024-02-20 22:03:30,756 basehttp 9868 2260 "POST /user/add/ HTTP/1.1" 200 827
INFO 2024-02-20 22:03:32,986 basehttp 9868 2260 "POST /user/add/ HTTP/1.1" 200 827
INFO 2024-02-20 22:13:41,263 autoreload 4072 3996 Watching for file changes with StatReloader
INFO 2024-02-20 22:13:48,434 basehttp 4072 12756 "POST /user/add/ HTTP/1.1" 200 827
INFO 2024-02-20 22:13:53,488 basehttp 4072 12756 "POST /user/add/ HTTP/1.1" 200 827
INFO 2024-02-20 22:13:54,358 basehttp 4072 12756 "POST /user/add/ HTTP/1.1" 200 827
INFO 2024-02-20 22:53:15,176 autoreload 8636 16780 Watching for file changes with StatReloader
INFO 2024-02-20 22:53:38,013 basehttp 8636 13768 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 22:55:06,656 basehttp 8636 13768 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 22:55:10,412 basehttp 8636 13768 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 22:57:07,988 basehttp 8636 13768 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 22:57:08,467 autoreload 8636 16780 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py changed, reloading.
INFO 2024-02-20 22:57:09,136 autoreload 14000 10236 Watching for file changes with StatReloader
INFO 2024-02-20 22:57:42,394 autoreload 14000 10236 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myproject\settings.py changed, reloading.
INFO 2024-02-20 22:57:43,065 autoreload 15252 13004 Watching for file changes with StatReloader
INFO 2024-02-20 22:57:43,994 basehttp 15252 16396 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 22:57:45,141 basehttp 15252 16396 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 22:58:15,552 basehttp 15252 16396 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 22:58:17,501 basehttp 15252 16396 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 22:58:18,169 basehttp 15252 16396 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 22:59:39,508 basehttp 15252 16396 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 22:59:39,975 autoreload 15252 13004 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py changed, reloading.
INFO 2024-02-20 22:59:40,618 autoreload 10936 11516 Watching for file changes with StatReloader
INFO 2024-02-20 22:59:40,788 basehttp 10936 17448 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 22:59:43,119 basehttp 10936 17448 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 22:59:48,992 basehttp 10936 17448 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 22:59:49,500 basehttp 10936 17448 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 23:00:46,879 basehttp 10936 17448 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 23:00:51,338 basehttp 10936 17448 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 23:00:52,664 basehttp 10936 17448 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 23:00:53,820 basehttp 10936 17448 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 23:01:54,896 basehttp 10936 17448 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 23:01:57,144 basehttp 10936 17448 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 23:02:12,437 basehttp 10936 17448 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 23:02:14,474 basehttp 10936 17448 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 23:02:17,595 basehttp 10936 17448 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 23:02:58,499 basehttp 10936 17448 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 23:02:59,408 autoreload 10936 11516 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py changed, reloading.
INFO 2024-02-20 23:03:00,075 autoreload 1692 15016 Watching for file changes with StatReloader
INFO 2024-02-20 23:03:04,190 basehttp 1692 17168 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 23:03:05,894 basehttp 1692 17168 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 23:03:19,496 basehttp 1692 17168 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 23:03:23,893 basehttp 1692 17168 "GET / HTTP/1.1" 200 388
INFO 2024-02-20 23:04:45,429 autoreload 1692 15016 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py changed, reloading.
INFO 2024-02-20 23:04:46,068 autoreload 15976 13744 Watching for file changes with StatReloader
INFO 2024-02-20 23:05:03,756 basehttp 15976 17676 "GET /user/add/ HTTP/1.1" 200 776
INFO 2024-02-20 23:05:25,733 views 15976 17676 Получили name='name12', email='sffsdgg2@mail.ru', age=28.
INFO 2024-02-20 23:05:25,736 basehttp 15976 17676 "POST /user/add/ HTTP/1.1" 200 827
INFO 2024-02-20 23:05:50,241 views 15976 17676 Получили name='name12', email='sffsdgg2@mail.ru', age=28.
INFO 2024-02-20 23:05:50,244 basehttp 15976 17676 "POST /user/add/ HTTP/1.1" 200 827
INFO 2024-02-20 23:11:02,266 autoreload 15976 13744 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\forms.py changed, reloading.
INFO 2024-02-20 23:11:02,933 autoreload 16068 7732 Watching for file changes with StatReloader
INFO 2024-02-20 23:11:16,008 autoreload 16068 7732 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\forms.py changed, reloading.
INFO 2024-02-20 23:11:16,637 autoreload 4756 18308 Watching for file changes with StatReloader
INFO 2024-02-20 23:12:03,580 autoreload 4756 18308 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\urls.py changed, reloading.
INFO 2024-02-20 23:12:04,233 autoreload 16544 16912 Watching for file changes with StatReloader
INFO 2024-02-20 23:12:11,973 basehttp 16544 18024 "GET /add/ HTTP/1.1" 200 776
INFO 2024-02-20 23:12:26,378 views 16544 18024 Получили name='tadles5', email='sffsdgg11@mail.ru', age=24.
INFO 2024-02-20 23:12:26,381 basehttp 16544 18024 "POST /add/ HTTP/1.1" 200 829
INFO 2024-02-20 23:16:47,160 autoreload 16544 16912 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py changed, reloading.
INFO 2024-02-20 23:16:47,791 autoreload 8408 17372 Watching for file changes with StatReloader
INFO 2024-02-20 23:18:00,042 autoreload 8408 17372 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py changed, reloading.
INFO 2024-02-20 23:18:00,758 autoreload 14164 16928 Watching for file changes with StatReloader
INFO 2024-02-20 23:21:24,993 autoreload 14164 16928 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\urls.py changed, reloading.
INFO 2024-02-20 23:21:25,621 autoreload 16488 18116 Watching for file changes with StatReloader
ERROR 2024-02-20 23:21:41,952 log 16488 16720 Internal Server Error: /add2/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py", line 31, in form2_app4
    return render(request, 'form2_app4.html', {'form': form})
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: form2_app4.html
ERROR 2024-02-20 23:21:41,955 basehttp 16488 16720 "GET /add2/ HTTP/1.1" 500 80742
INFO 2024-02-20 23:24:29,176 autoreload 16488 18116 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\forms.py changed, reloading.
INFO 2024-02-20 23:24:29,808 autoreload 17176 17432 Watching for file changes with StatReloader
INFO 2024-02-20 23:24:32,825 basehttp 17176 17744 "GET /add/ HTTP/1.1" 200 776
INFO 2024-02-20 23:26:08,738 autoreload 17176 17432 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\urls.py changed, reloading.
INFO 2024-02-20 23:26:09,393 autoreload 17596 18060 Watching for file changes with StatReloader
ERROR 2024-02-20 23:26:15,932 log 17596 17452 Internal Server Error: /add2/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py", line 31, in form2_app4
    return render(request, 'form2_app4.html', {'form': form})
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: form2_app4.html
ERROR 2024-02-20 23:26:15,934 basehttp 17596 17452 "GET /add2/ HTTP/1.1" 500 80742
INFO 2024-02-20 23:31:01,459 autoreload 17596 18060 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\forms.py changed, reloading.
INFO 2024-02-20 23:31:02,085 autoreload 13428 11936 Watching for file changes with StatReloader
INFO 2024-02-20 23:31:23,313 autoreload 13428 11936 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\forms.py changed, reloading.
INFO 2024-02-20 23:31:23,962 autoreload 18020 16208 Watching for file changes with StatReloader
ERROR 2024-02-20 23:31:25,539 log 18020 17060 Internal Server Error: /add2/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py", line 31, in form2_app4
    return render(request, 'form2_app4.html', {'form': form})
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: form2_app4.html
ERROR 2024-02-20 23:31:25,542 basehttp 18020 17060 "GET /add2/ HTTP/1.1" 500 80879
INFO 2024-02-20 23:35:18,208 autoreload 18020 16208 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myproject\urls.py changed, reloading.
INFO 2024-02-20 23:35:18,831 autoreload 15500 14704 Watching for file changes with StatReloader
INFO 2024-02-20 23:35:36,624 basehttp 15500 10264 "GET /myapp4/add/ HTTP/1.1" 200 776
ERROR 2024-02-20 23:35:43,670 log 15500 10264 Internal Server Error: /myapp4/add2/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py", line 31, in form2_app4
    return render(request, 'form2_app4.html', {'form': form})
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: form2_app4.html
ERROR 2024-02-20 23:35:43,672 basehttp 15500 10264 "GET /myapp4/add2/ HTTP/1.1" 500 80826
INFO 2024-02-20 23:37:13,680 basehttp 15500 10264 "GET /myapp4/add/ HTTP/1.1" 200 776
INFO 2024-02-20 23:41:32,676 autoreload 15500 14704 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myproject\settings.py changed, reloading.
INFO 2024-02-20 23:41:33,306 autoreload 7312 17224 Watching for file changes with StatReloader
INFO 2024-02-20 23:43:10,741 autoreload 7312 17224 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py changed, reloading.
INFO 2024-02-20 23:43:11,403 autoreload 16196 17344 Watching for file changes with StatReloader
INFO 2024-02-20 23:44:25,801 autoreload 16196 17344 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py changed, reloading.
INFO 2024-02-20 23:44:26,562 autoreload 17016 3960 Watching for file changes with StatReloader
INFO 2024-02-20 23:50:02,241 autoreload 17016 3960 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\urls.py changed, reloading.
INFO 2024-02-20 23:50:02,919 autoreload 8112 15672 Watching for file changes with StatReloader
INFO 2024-02-20 23:53:29,764 autoreload 8112 15672 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py changed, reloading.
INFO 2024-02-20 23:53:30,410 autoreload 10348 8652 Watching for file changes with StatReloader
INFO 2024-02-20 23:58:43,525 autoreload 10348 8652 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\urls.py changed, reloading.
INFO 2024-02-20 23:58:44,176 autoreload 17716 3984 Watching for file changes with StatReloader
ERROR 2024-02-20 23:59:10,501 log 17716 11020 Internal Server Error: /myapp4/upload/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py", line 46, in upload_image
    return render(request, 'myapp4/upload_image.html', {'form':form})
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp4/upload_image.html
ERROR 2024-02-20 23:59:10,502 basehttp 17716 11020 "GET /myapp4/upload/ HTTP/1.1" 500 81187
INFO 2024-02-21 00:00:35,451 basehttp 17716 11020 "GET /myapp4/add/ HTTP/1.1" 200 776
INFO 2024-02-21 00:02:57,513 autoreload 17716 3984 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\forms.py changed, reloading.
INFO 2024-02-21 00:02:58,177 autoreload 8188 16932 Watching for file changes with StatReloader
INFO 2024-02-21 00:04:30,580 autoreload 8188 16932 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\urls.py changed, reloading.
INFO 2024-02-21 00:04:31,238 autoreload 17508 5648 Watching for file changes with StatReloader
INFO 2024-02-21 00:06:14,816 autoreload 17508 5648 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py changed, reloading.
INFO 2024-02-21 00:06:15,471 autoreload 17748 10772 Watching for file changes with StatReloader
INFO 2024-02-21 00:08:15,654 autoreload 17748 10772 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\urls.py changed, reloading.
INFO 2024-02-21 00:08:16,292 autoreload 3896 17352 Watching for file changes with StatReloader
ERROR 2024-02-21 00:08:18,506 log 3896 13380 Internal Server Error: /myapp4/add/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py", line 22, in form_app4
    form = UserForm()
NameError: name 'UserForm' is not defined
ERROR 2024-02-21 00:08:18,506 basehttp 3896 13380 "GET /myapp4/add/ HTTP/1.1" 500 65954
INFO 2024-02-21 00:08:47,859 autoreload 3896 17352 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\forms.py changed, reloading.
INFO 2024-02-21 00:08:48,520 autoreload 16916 16436 Watching for file changes with StatReloader
ERROR 2024-02-21 00:08:49,987 log 16916 7208 Internal Server Error: /myapp4/add/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py", line 22, in form_app4
    form = UserForm()
NameError: name 'UserForm' is not defined
ERROR 2024-02-21 00:08:49,990 basehttp 16916 7208 "GET /myapp4/add/ HTTP/1.1" 500 65954
ERROR 2024-02-21 00:08:54,907 log 16916 7208 Internal Server Error: /myapp4/add/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py", line 22, in form_app4
    form = UserForm()
NameError: name 'UserForm' is not defined
ERROR 2024-02-21 00:08:54,908 basehttp 16916 7208 "GET /myapp4/add/ HTTP/1.1" 500 65954
INFO 2024-02-21 00:09:51,664 autoreload 16916 16436 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py changed, reloading.
INFO 2024-02-21 00:09:52,292 autoreload 11896 14964 Watching for file changes with StatReloader
INFO 2024-02-21 00:09:54,529 basehttp 11896 580 "GET /myapp4/add/ HTTP/1.1" 200 776
ERROR 2024-02-21 00:10:30,652 log 11896 580 Internal Server Error: /myapp4/upload/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py", line 46, in upload_image
    return render(request, 'upload_image.html', {'form':form})
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: upload_image.html
ERROR 2024-02-21 00:10:30,654 basehttp 11896 580 "GET /myapp4/upload/ HTTP/1.1" 500 81047
INFO 2024-02-21 00:12:02,175 autoreload 11896 14964 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\urls.py changed, reloading.
INFO 2024-02-21 00:12:02,813 autoreload 6936 9868 Watching for file changes with StatReloader
ERROR 2024-02-21 00:12:05,054 log 6936 12900 Internal Server Error: /myapp4/upload/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py", line 46, in upload_image
    return render(request, 'upload_image.html', {'form':form})
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: upload_image.html
ERROR 2024-02-21 00:12:05,057 basehttp 6936 12900 "GET /myapp4/upload/ HTTP/1.1" 500 81184
ERROR 2024-02-21 00:12:59,517 log 6936 12900 Internal Server Error: /myapp4/upload/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py", line 46, in upload_image
    return render(request, 'upload_image.html', {'form':form})
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: upload_image.html
ERROR 2024-02-21 00:12:59,519 basehttp 6936 12900 "GET /myapp4/upload/ HTTP/1.1" 500 81184
INFO 2024-02-21 00:13:55,798 autoreload 1972 10572 Watching for file changes with StatReloader
INFO 2024-02-21 00:16:17,294 basehttp 1972 16760 "GET /myapp4/add/ HTTP/1.1" 200 776
INFO 2024-02-21 00:16:36,912 basehttp 1972 16760 "GET /myapp4/add/ HTTP/1.1" 200 776
INFO 2024-02-21 00:17:13,775 autoreload 1972 10572 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\urls.py changed, reloading.
INFO 2024-02-21 00:17:14,407 autoreload 18136 10236 Watching for file changes with StatReloader
INFO 2024-02-21 00:17:15,643 basehttp 18136 18396 "GET /myapp4/add/ HTTP/1.1" 200 776
INFO 2024-02-21 00:17:23,668 basehttp 18136 18396 "GET /myapp4/add/upload/ HTTP/1.1" 200 587
ERROR 2024-02-21 00:23:20,506 log 18136 5568 Internal Server Error: /myapp4/add/upload/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py", line 40, in upload_image
    if form.is_valid():
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\forms.py", line 197, in is_valid
    return self.is_bound and not self.errors
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\forms.py", line 327, in full_clean
    self._clean_fields()
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\forms.py", line 337, in _clean_fields
    value = field.clean(value, bf.initial)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\fields.py", line 689, in clean
    return super().clean(data)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\fields.py", line 204, in clean
    value = self.to_python(value)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\fields.py", line 716, in to_python
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
ERROR 2024-02-21 00:23:20,509 basehttp 18136 5568 "POST /myapp4/add/upload/ HTTP/1.1" 500 95079
ERROR 2024-02-21 00:24:04,444 log 18136 5568 Internal Server Error: /myapp4/add/upload/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py", line 40, in upload_image
    if form.is_valid():
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\forms.py", line 197, in is_valid
    return self.is_bound and not self.errors
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\forms.py", line 327, in full_clean
    self._clean_fields()
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\forms.py", line 337, in _clean_fields
    value = field.clean(value, bf.initial)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\fields.py", line 689, in clean
    return super().clean(data)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\fields.py", line 204, in clean
    value = self.to_python(value)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\fields.py", line 716, in to_python
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
ERROR 2024-02-21 00:24:04,447 basehttp 18136 5568 "POST /myapp4/add/upload/ HTTP/1.1" 500 95079
INFO 2024-02-21 00:24:37,564 basehttp 18136 5568 "GET /myapp4/add/ HTTP/1.1" 200 776
INFO 2024-02-21 00:24:38,822 basehttp 18136 5568 "GET /myapp4/add/ HTTP/1.1" 200 776
INFO 2024-02-21 00:24:45,643 basehttp 18136 5568 "GET /myapp4/add/upload/ HTTP/1.1" 200 587
ERROR 2024-02-21 00:26:28,993 log 18136 5568 Internal Server Error: /myapp4/add/upload/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py", line 40, in upload_image
    if form.is_valid():
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\forms.py", line 197, in is_valid
    return self.is_bound and not self.errors
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\forms.py", line 327, in full_clean
    self._clean_fields()
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\forms.py", line 337, in _clean_fields
    value = field.clean(value, bf.initial)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\fields.py", line 689, in clean
    return super().clean(data)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\fields.py", line 204, in clean
    value = self.to_python(value)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\forms\fields.py", line 716, in to_python
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
ERROR 2024-02-21 00:26:28,995 basehttp 18136 5568 "POST /myapp4/add/upload/ HTTP/1.1" 500 95079
INFO 2024-02-21 00:29:13,378 basehttp 18136 5568 "POST /myapp4/add/upload/ HTTP/1.1" 200 587
INFO 2024-02-21 00:29:22,941 basehttp 18136 5568 "POST /myapp4/add/upload/ HTTP/1.1" 200 587
INFO 2024-02-21 00:32:33,289 autoreload 18136 10236 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\urls.py changed, reloading.
INFO 2024-02-21 00:32:34,412 autoreload 18152 5340 Watching for file changes with StatReloader
INFO 2024-02-21 00:37:35,462 autoreload 18152 5340 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\forms.py changed, reloading.
INFO 2024-02-21 00:37:36,119 autoreload 17188 11380 Watching for file changes with StatReloader
INFO 2024-02-21 00:37:42,390 basehttp 17188 17424 "GET /myapp4/add/ HTTP/1.1" 200 776
INFO 2024-02-21 00:37:45,911 basehttp 17188 17424 "GET /myapp4/add/add2 HTTP/1.1" 301 0
ERROR 2024-02-21 00:37:45,953 log 17188 1672 Internal Server Error: /myapp4/add/add2/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py", line 34, in form2_app4
    return render(request, 'form2_app4.html', {'form': form})
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: form2_app4.html
ERROR 2024-02-21 00:37:45,955 basehttp 17188 1672 "GET /myapp4/add/add2/ HTTP/1.1" 500 81934
INFO 2024-02-21 00:38:27,949 autoreload 17188 11380 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\urls.py changed, reloading.
INFO 2024-02-21 00:38:28,639 autoreload 3864 18076 Watching for file changes with StatReloader
INFO 2024-02-21 00:38:35,130 basehttp 3864 4068 "GET /myapp4/add/add2/form HTTP/1.1" 301 0
ERROR 2024-02-21 00:38:35,165 log 3864 17256 Internal Server Error: /myapp4/add/add2/form/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py", line 34, in form2_app4
    return render(request, 'form2_app4.html', {'form': form})
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: form2_app4.html
ERROR 2024-02-21 00:38:35,168 basehttp 3864 17256 "GET /myapp4/add/add2/form/ HTTP/1.1" 500 81994
INFO 2024-02-21 00:39:03,246 autoreload 3864 18076 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\urls.py changed, reloading.
INFO 2024-02-21 00:39:03,913 autoreload 17780 17832 Watching for file changes with StatReloader
INFO 2024-02-21 00:39:05,465 basehttp 17780 11960 "GET /myapp4/add/ HTTP/1.1" 200 776
INFO 2024-02-21 00:39:11,125 basehttp 17780 11960 "GET /myapp4/add2 HTTP/1.1" 301 0
ERROR 2024-02-21 00:39:11,160 log 17780 2496 Internal Server Error: /myapp4/add2/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py", line 34, in form2_app4
    return render(request, 'form2_app4.html', {'form': form})
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: form2_app4.html
ERROR 2024-02-21 00:39:11,164 basehttp 17780 2496 "GET /myapp4/add2/ HTTP/1.1" 500 81886
INFO 2024-02-21 00:39:48,342 autoreload 17780 17832 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\urls.py changed, reloading.
INFO 2024-02-21 00:39:49,039 autoreload 9608 18024 Watching for file changes with StatReloader
INFO 2024-02-21 00:40:13,863 autoreload 9608 18024 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\forms.py changed, reloading.
INFO 2024-02-21 00:40:14,552 autoreload 16924 580 Watching for file changes with StatReloader
INFO 2024-02-21 00:40:51,765 autoreload 16924 580 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py changed, reloading.
INFO 2024-02-21 00:40:52,386 autoreload 16604 11800 Watching for file changes with StatReloader
INFO 2024-02-21 00:41:06,250 autoreload 16604 11800 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py changed, reloading.
INFO 2024-02-21 00:41:06,896 autoreload 14192 16428 Watching for file changes with StatReloader
INFO 2024-02-21 00:41:07,132 basehttp 14192 17476 "GET /myapp4/add/upload/ HTTP/1.1" 200 587
INFO 2024-02-21 00:41:17,710 basehttp 14192 17476 "GET /myapp4/add/ HTTP/1.1" 200 776
INFO 2024-02-21 00:41:18,937 basehttp 14192 17476 "GET /myapp4/add/ HTTP/1.1" 200 776
INFO 2024-02-21 19:04:38,093 autoreload 8724 10928 Watching for file changes with StatReloader
INFO 2024-02-21 19:04:41,499 basehttp 8724 9860 "GET / HTTP/1.1" 200 388
WARNING 2024-02-21 19:04:41,667 log 8724 9860 Not Found: /favicon.ico
WARNING 2024-02-21 19:04:41,668 basehttp 8724 9860 "GET /favicon.ico HTTP/1.1" 404 2655
INFO 2024-02-21 19:06:54,853 autoreload 8724 10928 C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\urls.py changed, reloading.
INFO 2024-02-21 19:06:55,506 autoreload 10352 17940 Watching for file changes with StatReloader
INFO 2024-02-21 19:06:59,548 basehttp 10352 8988 "GET / HTTP/1.1" 200 388
WARNING 2024-02-21 19:07:18,996 log 10352 8988 Not Found: /add/
WARNING 2024-02-21 19:07:18,998 basehttp 10352 8988 "GET /add/ HTTP/1.1" 404 2634
WARNING 2024-02-21 19:08:48,069 log 10352 8988 Not Found: /add/upload/
WARNING 2024-02-21 19:08:48,069 basehttp 10352 8988 "GET /add/upload/ HTTP/1.1" 404 2655
INFO 2024-02-21 19:09:35,293 basehttp 10352 8988 "GET /myapp4/add/ HTTP/1.1" 200 776
INFO 2024-02-21 19:10:27,477 basehttp 10352 8988 "GET /myapp4/add/upload/ HTTP/1.1" 200 587
WARNING 2024-02-21 19:11:07,777 log 10352 8988 Not Found: /myapp4/add/upload_product_photo/
WARNING 2024-02-21 19:11:07,778 basehttp 10352 8988 "GET /myapp4/add/upload_product_photo/ HTTP/1.1" 404 3168
WARNING 2024-02-21 19:11:36,127 log 10352 8988 Not Found: /myapp4/add/upload_product_photo/
WARNING 2024-02-21 19:11:36,129 basehttp 10352 8988 "GET /myapp4/add/upload_product_photo/ HTTP/1.1" 404 3168
INFO 2024-02-21 19:11:57,515 basehttp 10352 8988 "GET /myapp4/add/upload2/ HTTP/1.1" 200 1443
ERROR 2024-02-21 19:15:17,581 log 10352 8988 Internal Server Error: /myapp4/add/upload2/
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\myproject\myapp4\views.py", line 57, in upload_product_photo
    return redirect('product_detail', pk=product.pk)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\Aleksandr\PycharmProjects\Django_project_2\venv\lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'product_detail' not found. 'product_detail' is not a valid view function or pattern name.
ERROR 2024-02-21 19:15:17,584 basehttp 10352 8988 "POST /myapp4/add/upload2/ HTTP/1.1" 500 86180
